
version: "3.7"

services:
  consul:
    image: consul
    command: "agent -dev -client 0.0.0.0"
    ports:
      - "8300:8300"
      - "8500:8500"

  cdp: &cdp-source
    image: golang:1.14.2
    container_name: cdp
    volumes:
      - cdp:/go/
      - go-build-cache:/root/.cache/go-build
      - .:${PROJECT_PATH}
    command: >
      sh -c "echo 'spin up caddy proxy cache...' &&
      cd ${PROJECT_PATH} &&
      go run $PROJECT_PATH/cmd/main.go run --config example/distributed_cache/Caddyfile"
    ports:
      - "9991:9991"
    environment:
      - PROJECT_PATH=${PROJECT_PATH}
    depends_on:
      - consul

  cdp2:
    <<: *cdp-source
    container_name: cdp2
    ports:
      - "9992:9991"

  cdp3:
    <<: *cdp-source
    container_name: cdp3
    ports:
      - "9993:9991"

  cdp4:
    <<: *cdp-source
    container_name: cdp4
    ports:
      - "9994:9991"

  file:
    <<: *cdp-source
    container_name: file
    ports:
      - "9995:9995"

    command: >
      sh -c "echo 'spin up caddy proxy cache...' &&
      cd ${PROJECT_PATH} &&
      go run $PROJECT_PATH/cmd/main.go run --adapter caddyfile --config example/distributed_cache/sourceCaddyfile"

    
volumes:
  cdp:
  go-build-cache:

